### ISSUE TITLE
Error cloning repository

### ISSUE THREAD

**Issue by IAmSalvaMartini** [iamshubhamg/Leet-Code#89]
Downloading as ZIP doesn't work either  

`error: invalid path '"Guess the number" game'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'`

**Comment by Aravindhsiva** [comment]
This is what I Dm'ed you @iamshubhamg bro, two days ago.... this is the same error I got, when i tried to clone...
